#!/usr/bin/env bash
set -e

FILENAME=$1

[ "$FILENAME" == "" ] && { echo 'Usage: ./package-client [package.tar.gz|output-dir]'; exit 1; }
[ ! -f "browser/index.html" ] && { echo 'browser/index.html not found in module'; exit 1; }
[ ! -f "browser/index.js" ] && { echo 'browser/index.js not found in module'; exit 1; }

dist=/tmp/form-dist
[ -d $dist ] && { rm -r $dist; }
mkdir $dist

node_modules/.bin/browserify browser/index.js -o $dist/index.js
node_modules/.bin/node-sass browser/styles/main.scss main.tmp && mv main.tmp $dist/main.css
cp browser/index.html $dist/

if [[ "$FILENAME" == *.tar.gz ]]; then
  dest="`pwd`/$FILENAME"
  (cd $dist && tar -czf "$dest" *)
else
  [ -d $FILENAME ] || { mkdir -p $FILENAME; }
  cp -r $dist/* $FILENAME
fi
rm -r $dist

echo $FILENAME created
